server:
  port: 70
spring:
  datasource:
    url: jdbc:postgresql://185.217.131.87/tedauzbot
    username: admin
    password: turgun1970
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
  sql:
    init:
      mode: never
  servlet:
    multipart:
      max-request-size: 5MB
      max-file-size: 5MB
telegram:
  bot:
   username: Uzb_Namaz_Times_bot
   token: 5082104093:AAE0li1xLe-TzHeUHGQ7l5kOps628wnXI-k