server:
  port: 70
spring:
  datasource:
    url: jdbc:postgresql://185.217.131.39/tedauzbot
    username: admin
    password: turgun1970
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  servlet:
    multipart:
      max-request-size: 20MB
      max-file-size: 20MB
telegram_bot_username: tedauz_bot
telegram_bot_botToken: 5432072116:AAF2651m2xXWtr90dSoffJoctHKDpmEHvq0